export const REVIEWS = [
  {
    id: 1,
    name: 'Kaya',
    date: '22 ноя 2024 20:23',
    stars: 4,
    text: 'Всё прошло хорошо',
    crypto: {
      from: 'USDT',
      to: 'TRX',
      amount: 10,
      rate: 51,
    },
  },
  {
    id: 2,
    name: 'Мария',
    date: '2023-10-02',
    stars: 4,
    text: 'Очень доволен работой команды.',
    crypto: {
      from: 'ETH',
      to: 'USDT',
      amount: 1,
      rate: 3000,
    },
  },
  {
    id: 3,
    name: 'Иван',
    date: '2023-10-01',
    stars: 5,
    text: 'Отличный сервис! Рекомендую всем.',
    crypto: {
      from: 'BTC',
      to: 'ETH',
      amount: 0.1,
      rate: 2000,
    },
  },
  {
    id: 4,
    name: 'Иван',
    date: '2023-10-01',
    stars: 1,
    text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to MAKE A TYPE specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    crypto: {
      from: 'BTC',
      to: 'ETH',
      amount: 0.1,
      rate: 2000,
    },
  },
  {
    id: 5,
    name: 'Иван',
    date: '2023-10-01',
    stars: 5,
    text: 'Отличный сервис! Рекомендую всем.',
    crypto: {
      from: 'BTC',
      to: 'ETH',
      amount: 0.1,
      rate: 2000,
    },
  },
];
